DROP TABLE IF EXISTS SALES_OFFICE CASCADE;
DROP TABLE IF EXISTS SALES_STAFF;
DROP TABLE IF EXISTS CUSTOMER;
DROP TABLE IF EXISTS STAFF_CUSTOMER;

CREATE TABLE IF NOT EXISTS SALES_OFFICE (
    OFFICE_ID SERIAL UNIQUE PRIMARY KEY,
    OFFICE_NAME VARCHAR(50),  
    STREET VARCHAR(50),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    ZIPCODE VARCHAR(50)
);


CREATE TABLE IF NOT EXISTS SALES_STAFF (
    EMP_ID SERIAL UNIQUE PRIMARY KEY,  
    OFFICE_ID INT,
	FOREIGN KEY (OFFICE_ID) REFERENCES SALES_OFFICE(OFFICE_ID),
	BIRTH_DATE DATE,
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    EMP_AGE INT
);


CREATE TABLE IF NOT EXISTS CUSTOMER (
    CUSTOMER_ID SERIAL UNIQUE PRIMARY KEY,
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
);


CREATE TABLE IF NOT EXISTS STAFF_CUSTOMER (
EMP_ID INT, 
CUSTOMER_ID INT,
foreign key (EMP_ID) references SALES_STAFF(EMP_ID),
foreign key (CUSTOMER_ID) references CUSTOMER(CUSTOMER_ID),
primary key (EMP_ID, CUSTOMER_ID)
);
